### ISSUE TITLE
Warnings und Notices auf den Addon-Seiten

### ISSUE THREAD

**Issue by DanielWeitenauer** [last-hero/square_shop#3]
Artikel, Kategorie, Bestellung, Kunde
Notice: Undefined index: type in `D:\xampp\htdocs\base_redaxo461\redaxo\include\addons\square_shop\classes\model\SSDBSQL.php on line 65`

Einstellung:
Eine ganze Menge, u.a.:
`Notice: Undefined index: settings in D:\xampp\htdocs\base_redaxo461\redaxo\include\addons\square_shop\pages\settings.inc.php on line 27`

`Warning: in_array() expects parameter 2 to be array, null given in D:\xampp\htdocs\base_redaxo461\redaxo\include\addons\square_shop\pages\settings.inc.php on line 27`

**Comment by prenzlweb** [comment]
Genau. Hier sind noch welche: 

Strict Standards: Non-static method SSHelper::array_keys_exists() should not be called statically, assuming $this from incompatible context in /kunden/133927_20146/2015/redaxo/include/addons/square_shop/classes/model/SSModel.php on line 100

**Comment by DanielWeitenauer** [comment]
Ich räume meine Issues auf und schließe hier, weil es inzwischen Version 5 gibt.
